#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python

python:
 - "3.7"

env:
 - CONFIG="-v --tb=short --cov=./ --cov-report xml"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:
 # Install packages
 - sudo apt-get install -y graphviz
 
 # Install llvm 10.0.0  
 - git clone https://github.com/llvm/llvm-project.git
 - git checkout llvm10.0.0
 - cd llvm-project
 - mkdir build
 - cd build
 - cmake -DLLVM_ENABLE_PROJECTS='polly;clang' -G "Unix Makefiles" ../llvm
 - make -j4
 - sudo make install

 # Install json
 
 - git clone https://github.com/nlohmann/json.git
 - mkdir build
 - cd build
 - cmake ../
 - make -j2
 - sudo make install

 - bash build_all.sh


#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

   #script:
        #bash build_all.sh
        #- py.test ../ $CONFIG

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------

        #after_success:
        #- codecov 
   #- bash <(curl -s https://codecov.io/bash)
