tmux new-session -d -s my_session_name7 'python -u run_morpher.py morpher_benchmarks/gemm/gemm.c gemm ./config/default_light_config.yaml > ./evaluate_data/gemm_default_light.txt'
tmux new-session -d -s my_session_name8 'python -u run_morpher.py morpher_benchmarks/array_add/array_add.c array_add ./config/default_light_config.yaml > ./evaluate_data/array_add_default_light.txt'
tmux new-session -d -s my_session_name9 'python -u run_morpher.py morpher_benchmarks/array_cond/array_cond.c array_cond ./config/default_light_config.yaml > ./evaluate_data/array_cond_default_light.txt'
tmux new-session -d -s my_session_name10 'python -u run_morpher.py morpher_benchmarks/fft/fix_fft.c fix_fft ./config/default_light_config.yaml > ./evaluate_data/fft_default_light.txt'
tmux new-session -d -s my_session_name11 'python -u run_morpher.py morpher_benchmarks/hpcg/hpcg.c hpcg ./config/default_light_config.yaml > ./evaluate_data/hpcg_default_light.txt'
tmux new-session -d -s my_session_name12 'python -u run_morpher.py morpher_benchmarks/trmm/trmm.c trmm ./config/default_light_config.yaml > ./evaluate_data/trmm_default_light.txt'
