tmux new-session -d -s my_session_name25 'python -u run_morpher.py morpher_benchmarks/gemm/gemm.c gemm ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/gemm_4x4.txt'
tmux new-session -d -s my_session_name26 'python -u run_morpher.py morpher_benchmarks/array_add/array_add.c array_add ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/array_add_4x4.txt'
tmux new-session -d -s my_session_name27 'python -u run_morpher.py morpher_benchmarks/array_cond/array_cond.c array_cond ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/array_cond_4x4.txt'
tmux new-session -d -s my_session_name28 'python -u run_morpher.py morpher_benchmarks/fft/fix_fft.c fix_fft ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/fft_4x4.txt'
tmux new-session -d -s my_session_name29 'python -u run_morpher.py morpher_benchmarks/hpcg/hpcg.c hpcg ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/hpcg_4x4.txt'
tmux new-session -d -s my_session_name30 'python -u run_morpher.py morpher_benchmarks/trmm/trmm.c trmm ./config/config_stdnoc4x4_cgrame.yaml > ./evaluate_data/trmm_4x4txt'
