---
 json_arch: "stdnoc_allmem.json"
 json_arch_before_memupdate: 'stdnoc_allmem.json'
 mapper_subfolder: 'arch_stdnoc__dfgtype_cgrame'
 dfg_type: 'CGRAME'
 init_II: 0
 numberofbanks: 2
 banksize: 16384
 max_test_samples: 5
 mapping_method: 1
 llvm_debug_type: 'no'

