---
 json_arch: "hycube_8x8.json"
 json_arch_before_memupdate: 'hycube_8x8.json'
 mapper_subfolder: 'arch_stdnoc8x8__dfgtype_cgrame'
 dfg_type: 'PartPredLight'
 init_II: 0
 ydim: 8
 xdim: 8
 numberofbanks: 2
 banksize: 16384
 max_test_samples: 5
 mapping_method: 1
 llvm_debug_type: 'no'
 morpher_light: 'yes'
