---
 json_arch: "hycube_8x8.json"
 json_arch_before_memupdate: 'hycube_8x8.json'
 mapper_subfolder: 'hycube_8x8'
 dfg_type: 'PartPredLight'
 init_II: 0
 ydim: 4
 xdim: 4
 numberofbanks: 2
 banksize: 2048
 max_test_samples: 5
 mapping_method: 0
 llvm_debug_type: 'no'
 morpher_light: 'yes'

